# build with
#docker build -t chrome:2.0 -f Dockerfile.dev .

FROM markhobson/maven-chrome:jdk-11

RUN mkdir -p /logs
RUN mkdir -p /results
RUN chmod ugo+w /var
RUN chmod ugo+w /logs

ADD ./extentreports /extentreports
RUN chmod -R ugo+w /extentreports

ADD ./config.xml config.xml
RUN chmod -R ugo+w config.xml

ADD ./Datentreiber.xlsx Datentreiber.xlsx
RUN chmod ugo+w Datentreiber.xlsx


# Add App
ADD ./target/SeleniumTestobject-1.0-SNAPSHOT.war app.war
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.war"]